language: generic

script: bash ./compile.sh

branches:
  only:
    - master


before_deploy:
- openssl aes-256-cbc -K $encrypted_89bfa84225f8_key -iv $encrypted_89bfa84225f8_iv -in deploy_key.enc -out deploy_key -d

deploy:
  provider: pages
  local_dir: out
  deploy_key: deploy_key
  edge:
    branch: master

notifications:
  email:
    on_success: never
    on_failure: always
